version: '3.8'
services:
  exam-env:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/home/coder/project
    environment:
      - PASSWORD=esame # The password you will type in the browser
    restart: unless-stopped
