[package]
name = "lab03"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "my_implementation"
path = "src/my_implementation/main.rs"

[[bin]]
name = "solution"
path = "src/solution/main.rs"

[dependencies]
aggregator = "0.1.0"
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
regex = "1.12.3"
